### ISSUE TITLE
No color preview in the readme or the website page.

### ISSUE THREAD

**Issue by billybrown-iii** [dracula/tailwind#10]
As a developer picking this up for the first time, I would find it helpful if the readme had a preview image with a grid that shows the available colors and shades.

**Comment by nickgraffis** [comment]
Fair point @billybrown-iii! Handled this in #11

The [Dracula website](https://draculatheme.com/tailwind) has an image at the very top, an example of the colors in a tailwind play.

To not conflict with that image right at the top, I added an image of the colors to the INSTALL.md, which will end up on the bottom of the [Dracula website](https://draculatheme.com/tailwind). 

It takes time for the automatic builds to happen, but hopefully this is what you were looking for, thanks for the suggestion!
