### ISSUE TITLE
Request: Add TailWindCSS colour variants

### ISSUE THREAD

**Issue by h2ogeek** [dracula/tailwind#2]
I was wondering if you can add the additional the colour variants like TailWindCSS:

* bg-dracula-dracula (base)
* bg-dracula-dracula-50 ... bg-dracula-dracula-900

* text-dracula-dracula
* text-dracula-dracula-50 ... text-dracula-dracula-900

etc

**Comment by nickgraffis** [comment]
Hey! Cool idea. I am using [this tool](https://tw-shade-gen.netlify.app) to get the shades. This is a tricky process and isn't always perfect, choosing colors by hand seems like it might be the only way to make this perfect, but I think this is a solid feature!

Added in [this commit](https://github.com/dracula/tailwind/commit/110ab866d0eaa54491adcb50d9d0b98c2a1a57c1). It's [version 1.0.7](https://www.npmjs.com/package/tailwind-dracula)

**Comment by upupming** [comment]
Wow, I was just wondering how these values were computed, it seems TwailwindCSS chooses its built-in shades manually: https://tailwindcss.com/docs/customizing-colors#generating-colors, https://github.com/tailwindlabs/tailwindcss/issues/686. Thanks for sharing this tool! I also found [another different tool](https://www.tailwindshades.com/#color=37.69230769230769%2C92.12598425196852%2C50.19607843137255&step-up=8&step-down=11&hue-shift=0&name=buttercup&overrides=e30%3D) which changes only `lightness` of the HSL value of the color. Both helps!
