### ISSUE TITLE
Web page palette table broken.

### ISSUE THREAD

**Issue by anthonybench** [dracula/tailwind#9]
I posted an earlier issue, and although it was closed and some PR was merged, it doesn't appear to be fixed. Probably my fault from not clarifying.

When i go [here](https://draculatheme.com/tailwind), I see the following (attached).

looks like a broken markdown table, with some broken image links, but not sure.

Thanks!
<img width="931" alt="dracula_tailwind" src="https://github.com/dracula/tailwind/assets/36245150/b6fcaa6d-34eb-4f4b-b7d6-fe3bdc452790">

**Comment by nickgraffis** [comment]
Yeah I think the Dracula website builds on a nightly cron or something like that. not totally sure, but in #8 it is updated, it'll just take time to update on the actual site.

**Comment by anthonybench** [comment]
Ahh I see, then I'll close here
